#!/usr/bin/env node
/**
 * sync-videos.js — fetches the Obras del País YouTube uploads via the
 * Data API v3, joins them against artisans.json by slug or name match,
 * and writes /assets/data/videos.json.
 *
 * Usage:
 *   YOUTUBE_API_KEY=AIza... node scripts/sync-videos.js
 *   YOUTUBE_API_KEY=AIza... CHANNEL_HANDLE=@obrasdelpais node scripts/sync-videos.js
 *
 * To get an API key (free, no card required):
 *   1. https://console.cloud.google.com/  →  create a project
 *   2. APIs & Services → Library → enable "YouTube Data API v3"
 *   3. APIs & Services → Credentials → Create credentials → API key
 *   4. Restrict the key to "YouTube Data API v3" only
 *
 * To restrict abuse: also restrict by HTTP referrer to the live domain
 * before committing the key. For this script, the key is used server-side
 * (CLI) and never shipped to the browser.
 */

const fs = require("node:fs");
const path = require("node:path");

const API_KEY = process.env.YOUTUBE_API_KEY;
const HANDLE = process.env.CHANNEL_HANDLE || "@obrasdelpais";

if (!API_KEY) {
  console.error("Missing YOUTUBE_API_KEY env var. See file header for how to get one.");
  process.exit(1);
}

const root = path.join(__dirname, "..");
const artisansPath = path.join(root, "assets/data/artisans.json");
const videosPath = path.join(root, "assets/data/videos.json");
const artisans = JSON.parse(fs.readFileSync(artisansPath, "utf8"));

async function api(endpoint, params) {
  const url = new URL("https://www.googleapis.com/youtube/v3/" + endpoint);
  Object.entries({ ...params, key: API_KEY }).forEach(([k, v]) => url.searchParams.set(k, v));
  const r = await fetch(url);
  if (!r.ok) throw new Error(`${r.status} ${r.statusText} — ${await r.text()}`);
  return r.json();
}

function norm(s) {
  return s.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/[^a-z0-9]+/g, " ").trim();
}

function bestArtisan(title) {
  const t = norm(title);
  let best = null, bestScore = 0;
  for (const a of artisans) {
    const slugTokens = norm(a.slug).split(" ").filter((tk) => tk.length > 2);
    const nameTokens = norm(a.name).split(" ").filter((tk) => tk.length > 2);
    const tokens = [...new Set([...slugTokens, ...nameTokens])];
    let score = 0;
    for (const tk of tokens) if (t.includes(tk)) score += tk.length;
    if (score > bestScore) { bestScore = score; best = a; }
  }
  return bestScore >= 6 ? best : null;
}

(async () => {
  console.log(`Looking up channel for handle ${HANDLE}...`);
  const ch = await api("channels", { part: "contentDetails,snippet,statistics", forHandle: HANDLE });
  if (!ch.items || !ch.items.length) throw new Error(`No channel found for ${HANDLE}`);
  const channel = ch.items[0];
  const channelId = channel.id;
  const uploadsId = channel.contentDetails.relatedPlaylists.uploads;
  console.log(`Channel: ${channel.snippet.title} · ${channelId} · uploads playlist ${uploadsId}`);

  const videos = [];
  let pageToken;
  do {
    const page = await api("playlistItems", {
      part: "snippet,contentDetails",
      playlistId: uploadsId,
      maxResults: 50,
      ...(pageToken ? { pageToken } : {}),
    });
    for (const it of page.items) {
      const s = it.snippet;
      const matched = bestArtisan(s.title);
      videos.push({
        videoId: it.contentDetails.videoId,
        title_es: s.title,
        title_en: s.title,
        publishedAt: it.contentDetails.videoPublishedAt || s.publishedAt,
        thumbnail: s.thumbnails?.maxres?.url || s.thumbnails?.high?.url || null,
        slug: matched ? matched.slug : null,
        n: matched ? matched.n : null,
        place_es: matched ? matched.place_es : null,
        region_es: matched ? matched.region_es : null,
      });
    }
    pageToken = page.nextPageToken;
  } while (pageToken);

  videos.sort((a, b) => (b.n || 0) - (a.n || 0) || (b.publishedAt > a.publishedAt ? 1 : -1));

  const out = {
    _comment: "Generated by scripts/sync-videos.js. Do not edit manually — re-run the script to refresh.",
    channelId,
    uploadsPlaylistId: uploadsId,
    lastSyncedISO: new Date().toISOString(),
    videos,
  };
  fs.writeFileSync(videosPath, JSON.stringify(out, null, 2) + "\n");
  console.log(`Wrote ${videos.length} videos → ${videosPath}`);
  const matched = videos.filter((v) => v.slug).length;
  console.log(`Matched ${matched}/${videos.length} videos to artisan slugs.`);
})().catch((err) => {
  console.error("\nFailed:", err.message);
  process.exit(1);
});
