#!/usr/bin/env python3
"""
build-map-data.py — merge the agent-extracted municipios into artisans.json,
and emit a municipios.json aggregating municipio → list of artisans.

Run: python3 scripts/build-map-data.py
"""
import json, pathlib, unicodedata, re

ROOT = pathlib.Path(__file__).resolve().parent.parent
PREVIEW = ROOT / "preview-site"
THEME = ROOT / "obras-del-pais-theme"

# From the extraction agent
MUNI_BY_SLUG = {
    "antonio-nieves": "Caguas",
    "jorge-rivera-tornero-de-lajas": "Lajas",
    "gloria-lopez-estrella-talladora-de-santos": "Camuy",
    "alex-rios-tallador-de-aves": "Bayamón",
    "rafael-aviles-vazquez-lutier": "Carolina",
    "kenneth-melendez": "Lajas",
    "wanda-ramirez-flora-en-cuero": "Cabo Rojo",
    "eliseo-elo-molina": "Canóvanas",
    "norma-gomez-petate": "Sábana Grande",
    "teissonniere-tallador-de-gallos": "Ponce",
    "anna-nicholson-grabados": "San Juan",
    "nellie-y-sandra-tejedoras-de-mundillo": "Moca",
    "edwin-marcucci-cesteria": "Adjuntas",
    "jose-antonio-escultor-en-piedra": "Salinas",
    "nicholas-damiani-alfareria": "Bayamón",
    "lourdes-soto-ramos-metal-repujado": "Ponce",
    "masaro-perez-escultura-en-ceramica": "Aguas Buenas",
    "gerardo-hernandez-cortes-flautas-de-madera": "Isabela",
    "deborah-feliciano-fachadas-sobre-bambu": "San Juan",
    "teddy-vazquez-y-wilda-cruz": "Loíza",
    "teresa-melendez-munecas-de-trapo": "San Juan",
    "wilzen-cuco-perez-los-reyes-en-carretas": "Guánica",
    "gladys-serrano-textiles-tenidos": "Guaynabo",
    "guadalupe-villalobos-muebles-de-enea": "Ciales",
    "jose-hernandez-y-carmen-soto-hamacas": "San Sebastián",
    "iris-torres-talla-de-hueso": "Orocovis",
    "victor-ivan-sosa-casitas-tipicas-en-barro": "Carolina",
    "evelyn-vazquez-talla-de-madera": "Canóvanas",
    "juan-irizarry-artesano-tabaco": "Lares",
    "bacaju-artesania-como-practica-de-vida": "Bayamón",
    "angel-lopez-la-pava-sombrero-jibaro": "Aguada",
    "misael-fernandez-cuchilleria": "Naranjito",
    "limary-rivera-trajes-y-mascaras-de-vejigantes": "Ponce",
    "alice-cheverez-alfareria-ancestral": "Morovis",
    "pesca-artesanal-memorias": "Aguada",
    "ibsen-peralta-talla-de-santos": "Toa Alta",
    "milly-borrero-soles-de-naranjito": "Peñuelas",
    "rafael-y-rosa-juguetes-de-madera": "Bayamón",
}


def slugify(s):
    """Match the SVG's id format: lowercase ASCII kebab-case."""
    s = unicodedata.normalize("NFD", s)
    s = "".join(c for c in s if not unicodedata.combining(c))
    s = s.lower().replace("ñ", "n")
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s


# Update artisans.json
art_path = PREVIEW / "assets/data/artisans.json"
artisans = json.loads(art_path.read_text())
for a in artisans:
    muni = MUNI_BY_SLUG.get(a["slug"])
    if muni:
        a["municipio"] = muni
        a["municipio_slug"] = slugify(muni)
        # Backfill place_es when we now have a muni and it's missing
        if not a.get("place_es"):
            a["place_es"] = muni

art_path.write_text(json.dumps(artisans, ensure_ascii=False, indent=2) + "\n")
(THEME / "assets/data/artisans.json").write_text(art_path.read_text())
print(f"Updated artisans.json with {sum(1 for a in artisans if a.get('municipio'))} municipios.")

# Aggregate municipio → artisans
agg = {}
for a in artisans:
    muni = a.get("municipio")
    if not muni:
        continue
    key = a["municipio_slug"]
    agg.setdefault(key, {"name": muni, "slug": key, "artisans": []})
    agg[key]["artisans"].append({
        "slug": a["slug"],
        "name": a["name"],
        "n": a["n"],
        "craft_es": a["craft_es"],
        "craft_en": a["craft_en"],
        "image_cdn": a.get("image_cdn"),
        "videoId": a.get("videoId"),
        "asl": a.get("asl", False),
    })

# Sort artisans within each muni by their doc number
for v in agg.values():
    v["artisans"].sort(key=lambda x: x["n"])

# Sort munis alphabetically by canonical name
sorted_agg = dict(sorted(agg.items(), key=lambda kv: kv[1]["name"]))

out = {
    "_comment": "Generated by scripts/build-map-data.py. One entry per municipio that has at least one artisan; values are the canonical name (with diacritics) plus the SVG-matching slug and the list of artisans.",
    "total_artisans": len(artisans),
    "total_municipios_with_artisans": len(sorted_agg),
    "by_municipio": sorted_agg,
}

out_path = PREVIEW / "assets/data/municipios.json"
out_path.write_text(json.dumps(out, ensure_ascii=False, indent=2) + "\n")
(THEME / "assets/data/municipios.json").write_text(out_path.read_text())
print(f"Wrote municipios.json: {len(sorted_agg)} municipios covering {sum(len(v['artisans']) for v in sorted_agg.values())} artisans.")

# Print summary so we can verify
print("\nMunicipios covered:")
for slug, info in sorted_agg.items():
    n = len(info["artisans"])
    print(f"  {info['name']:18}  ({slug:18})  {n} artisan{'s' if n != 1 else ''}")
